#!/usr/bin/env python
#-*- coding:utf-8 -*-
#第一行注释可以让这个文件直接在unix/linux/mac上运行
#第二行表示.py文件本身使用标准utf-8编码
#如果想要引入一个模块必须要在同一个文件路径下
'a test module'
__author__='Michael Liao'

import sys
def test():
    args = sys.argv
    if len(args)==1:
        print 'Hello,world!'
    elif len(args)==2:
        print 'Hello,%s!' % args[1]
    else:
        print 'Too many arguments!'

if __name__=='__main__':
    test()

#!/usr/bin/env python
#-*- coding:utf-8 -*-

try:
    import  cStringIO as StringIO
except ImportError:#导入失败会捕获到ImportError
    import StringIO
#这样可以优先导入cStringIO

#类似simplejson这样的库，在python2.6之前是独立的第三
# 方库，从2.6开始内置，所以，会有这样的写法
try:
    import json #python>=2.6
except ImportError:
    import  simplejson as json #python <= 2.5
#python是动态语言，函数签名一致接口就一样，因此，无论
#无论导入哪个模块后续代码都能正常工作。
