#!/usr/bin/env python
#-*- coding:utf-8 -*-
#第一行注释可以让这个文件直接在unix/linux/mac上运行
#第二行表示.py文件本身使用标准utf-8编码
#如果想要引入一个模块必须要在同一个文件路径下
'a test module'
__author__='Michael Liao'

import sys
def test():
    args = sys.argv
    if len(args)==1:
        print 'Hello,world!'
    elif len(args)==2:
        print 'Hello,%s!' % args[1]
    else:
        print 'Too many arguments!'

if __name__=='__main__':
    test()
